### ISSUE TITLE
could not take picture because Auto Focus Failed

### ISSUE THREAD

**Issue by unruledboy** [esskar/Canon.Eos.Framework#10]
---
## Failed to take a picture.

Canon.Eos.Framework.EosException: Take Picture Auto Focus Failed.

Failed to take picture.

   at Canon.Eos.Framework.Helper.Util.Assert(UInt32 result, String message) in e:\TDDOWNLOAD\down\esskar-Canon.Eos.Framework-0aacd29\esskar-Canon.Eos.Framework-0aacd29\Canon.Eos.Framework\Helper\Util.cs:line 28

   at Canon.Eos.Framework.EosCamera.TakePicture() in e:\TDDOWNLOAD\down\esskar-Canon.Eos.Framework-0aacd29\esskar-Canon.Eos.Framework-0aacd29\Canon.Eos.Framework\EosCamera.cs:line 475

   at Canon.Eos.CameraCockpit.Forms.CockpitForm.<HandleTakePictureButtonClick>b__0() in e:\TDDOWNLOAD\down\esskar-Canon.Eos.Framework-0aacd29\esskar-Canon.Eos.Framework-0aacd29\Canon.Eos.CameraCockpit\Forms\CockpitForm.cs:line 99

   at Canon.Eos.CameraCockpit.Forms.CockpitForm.SafeCall(Action action, Action`1 exceptionHandler) in e:\TDDOWNLOAD\down\esskar-Canon.Eos.Framework-0aacd29\esskar-Canon.Eos.Framework-0aacd29\Canon.Eos.CameraCockpit\Forms\CockpitForm.cs:line 154

**Comment by unruledboy** [comment]
It will be fine after I disable the auto focus on the lens

**Comment by esskar** [comment]
Hi. Let me get back to this. My camera broke, so i had to get it fixed.

**Comment by simonbuehler** [comment]
i have no idea if this can be fixed as this also happens when you try to take a picture manually and it can't focus - it does not take one

**Comment by Bill-Lea** [comment]
Some cameras can be set to take a picture regardless of autofocus status.  I have not been able to find out if the Canons will do it. The thing is you need to allow for this sort of thing so you don't hang the application. Some times just trying again will cause the AF to work. Its either a matter of shutter priority or trying the shot some number of times either manually or automatically.

**Comment by ghost** [comment]
On my 40D this pops out when i.e. the camera lens cover is on. More generally - when the autofocus fails. All my Canons (40D, 60D, 450D and 1100D) refuse to shot when autofocus fails unless you manually turn it off.

**Comment by simonbuehler** [comment]
could be closed as a won'tfix
